### ISSUE TITLE
2048 game not working properly

### ISSUE THREAD

**Issue by PrajaktaSathe** [kiteco/python-youtube-code#11]
The game 2048 is not functioning properly. Is there a bug in there somewhere?

**Comment by Kordianz** [comment]
hello, I have this same problem:
Traceback (most recent call last):
  File "e:\projekty\python\2048.py", line 3, in <module>
    import colors as c
  File "e:\projekty\python\colors.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
PS E:\projekty>

Python 3.9.7
